### ISSUE TITLE
Fails to install if local bin folder does not exist on macOS

### ISSUE THREAD

**Issue by mvllow** [barelyhuman/goblin#4]
After trying to install [github.com/maaslalani/typer](https://github.com/maaslalani/typer) to the default location `/usr/local/bin` which does not currently exist on my system, it appears that `/usr/local/bin <-- file` was made instead of the folder being created and nothing installed

Edit: feel free to close if this is out of scope – changing the prefix is simple enough and the edge cases of something such as `mkdir -p $PREFIX` may outweigh the benefits

**Comment by barelyhuman** [comment]
> feel free to close if this is out of scope – changing the prefix is simple enough and the edge cases of something such as mkdir -p $PREFIX may outweigh the benefits

It's not really out of scope.

While I use goblin for CI engines to setup go based tools quickly, the other major use case is being able to install this for non-go lang based devs / users. 

also, `mkdir -p $PREFIX` has one problem that the user might not perms to handle the creation so it just won't be a `mkdir` it'll have to split similar to the `install` command setup in the script right now. 

I'll go through things that I might need to add to the script before I merge it as a fix

**Comment by barelyhuman** [comment]
@mvllow let me know if the current deploy handles it for you :)

**Comment by mvllow** [comment]
works beautifully, thanks!
