### ISSUE TITLE
Implement /binary/X?output query parameter

### ISSUE THREAD

**Issue by diamondburned** [barelyhuman/goblin#7]
The `?output` query parameter will be useful for outputting Windows binaries, since right now, they're not downloaded with the `.exe` extension. The server can implement this using the [`Content-Disposition`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) header.

**Comment by barelyhuman** [comment]
Good find and that could be a useful parameter as well, 

though I'll need someone on a windows system to test that out for me , before I merge it into the stable code.

**Comment by barelyhuman** [comment]
@diamondburned hey, could you try cloning the branch #8 is on and running a local docker to check if that satisfies your requirement?
